# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b46a5ec446340b915e827d919bac614a8a20634f53cc875c55a0042cd9e4218d2509e8f896d2c04ed06f555f8bece5241b0e88f2d8902eb8eec247384f658d1

test:
  secret_key_base: af8d01e6755b10f454c1a2b49326b1861a0b6fdb2133d2c8cef7b5c992383417b146e5fff84735bcfa275f383a0c66a3c84b30772d127f53b22303be994ebf40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
